#!/usr/bin/env bash

function main {
  case "${PLUGIN_TASK:-}" in
    fmt)
      cp .drone.yml /tmp/.drone.yml
      drone fmt --save /tmp/.drone.yml
      if diff .drone.yml /tmp/.drone.yml; then
        return 0
      fi

      if [[ -w .drone.yml ]]; then
        drone fmt --save
      fi

      return 1
      ;;

    lint)
      drone lint
      ;;
    *)
      echo "ERROR: unknown task setting: ${PLUGIN_TASK:-}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
