#!/usr/bin/env bash

function main {
  case "${PLUGIN_TASK:-}" in
    fmt)
      cp .drone.yml /tmp/.drone.yml
      drone fmt --save /tmp/.drone.yml
      diff .drone.yml /tmp/.drone.yml
      ;;
    lint)
      drone lint
      ;;
    *)
      echo "ERROR: unknown task setting: ${PLUGIN_TASK:-}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
